"""Add meeting.data JSONB column

Revision ID: dc59a1c03d1f
Revises: 0001_initial_schema
Create Date: 2025-06-07 21:50:48.189571

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision = 'dc59a1c03d1f'
down_revision = '0001_initial_schema'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Check if column already exists (created by initial migration)
    conn = op.get_bind()
    inspector = inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('meetings')]
    
    if 'data' not in columns:
        op.add_column('meetings', sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'{}'::jsonb")))
        op.create_index('ix_meeting_data_gin', 'meetings', ['data'], unique=False, postgresql_using='gin')
        op.execute("UPDATE meetings SET data = '{}'::jsonb WHERE data IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_meeting_data_gin', table_name='meetings', postgresql_using='gin')
    op.drop_column('meetings', 'data')
    # ### end Alembic commands ### 